version: "3.8"

services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
