name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack + Install dependencies
        run: |
          corepack enable
          pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Upload build via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: www
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/md2pdf/dist"

      - name: Upload Dockerfile and package.json (если нужно)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: www
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Dockerfile,package.json,pnpm-lock.yaml,docker-compose.yml"
          target: "/var/www/md2pdf/"

      - name: Restart app via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: www
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/md2pdf
            docker-compose down
            docker-compose up -d --build
